# Generated by Django 3.2.5 on 2021-07-20 13:52

import Cafe.validator
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, help_text='upload the category image', null=True, upload_to='categories/images/', verbose_name='category image')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='add menu item name to this field', max_length=50, verbose_name='menu item name')),
                ('price', models.FloatField(help_text='add price of menu item', verbose_name='price(dollar)')),
                ('discount', models.FloatField(help_text='insert the discount 0 to 100', validators=[Cafe.validator.discount_validator], verbose_name='discount')),
                ('serving_time_period', models.IntegerField(help_text='insert how much time spend to be served', null=True)),
                ('estimated_cooking_time', models.IntegerField(help_text='insert how much time spend to be cooked', null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(help_text='choose category', on_delete=django.db.models.deletion.CASCADE, to='Cafe.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(auto_created=True)),
                ('status', models.CharField(max_length=50)),
                ('datetime_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time that order recorded')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='enter number of table', verbose_name='table number')),
                ('position', models.CharField(help_text='enter position of table', max_length=50, verbose_name='table position')),
                ('status', models.IntegerField(default=0, help_text='status of table at the moment', verbose_name='table status')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='price of order')),
                ('final_price', models.IntegerField(verbose_name='price of order with discounts')),
                ('date_time_stamp', models.DateTimeField(verbose_name='publish time of receipt')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='enter number of item you want', verbose_name='number of menu item that ordered')),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe.menuitem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(through='Cafe.OrderMenuItem', to='Cafe.MenuItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cafe.table'),
        ),
    ]
