# Generated by Django 3.2.5 on 2021-07-20 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish time of receipt'),
        ),
    ]
