# Generated by Django 3.2.5 on 2021-07-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0003_alter_receipt_date_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time that order recorded'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(auto_created=5765849),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, help_text='choose between 0,1,2', verbose_name='set status of this order'),
        ),
    ]
