# Generated by Django 3.2.5 on 2021-07-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0004_auto_20210721_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=7931016),
        ),
    ]
